name "gpg"
maintainer       "Heavy Water"
maintainer_email "support@hw-ops.com"
license          "Apache 2.0"
description      "GPG install/config/helpers"
long_description "GPG install/config/helpers"
version          "0.2.3"
