default[:gpg][:package][:name] = 'gpg'
default[:gpg][:package][:version] = nil
default[:gpg][:package][:action] = :install # or :upgrade
default[:gpg][:databag] = 'gpg'

# This will auto generate local key. It is provided for compat reasons
# and will use the values below for key generation
default[:gpg][:auto_generate] = false

# These attributes remain to ease compat with previous versions
default[:gpg][:name][:real] = 'Default'
default[:gpg][:name][:comment] = 'Generated by Chef'
default[:gpg][:name][:email] = "#{node.name}@example.com"
default[:gpg][:expire][:date] = 0
default[:gpg][:key_type] = 'RSA'
default[:gpg][:key_length] = 2048
default[:gpg][:override_default_keyring] = false
default[:gpg][:pubring_file] = nil
default[:gpg][:secring_file] = nil
default[:gpg][:user] = 'root'
